# Generated by Django 3.2.9 on 2021-12-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'percent'), (2, 'value')], default=1)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
