# Generated by Django 3.2.9 on 2021-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='amount',
            field=models.FloatField(default=13),
        ),
    ]
