# Generated by Django 3.2.9 on 2021-12-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_alter_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='appSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.TextField(blank=True, null=True)),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='system/')),
                ('terms', models.TextField(blank=True, null=True)),
                ('privacy', models.TextField(blank=True, null=True)),
                ('aboutUs', models.TextField(blank=True, null=True)),
                ('versionNumber', models.TextField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('github', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintainanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='MaintainanceMode', null=True)),
            ],
        ),
    ]
