# Generated by Django 3.2.9 on 2021-12-23 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0004_auto_20211223_1425'),
        ('Settings', '0002_alter_tax_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.IntegerField(default=0)),
                ('receiptNo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='order_items_relation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('billNo', models.IntegerField(default=0)),
                ('receiptNo', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'Preparing'), (3, 'delivering'), (4, 'delivered')], default=1)),
                ('isActive', models.BooleanField(default=False)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('order_number', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('taxAmount', models.FloatField(blank=True, null=True)),
                ('shipAmount', models.FloatField(blank=True, null=True)),
                ('extraAmount', models.FloatField(blank=True, null=True)),
                ('couponAmount', models.FloatField(blank=True, null=True)),
                ('discountAmount', models.FloatField(blank=True, null=True)),
                ('grandAmount', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('deliveryPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_person_realtion', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, to='Order.OrderItem', verbose_name='order_items_relation')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Settings.tax')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='order_user_relation')),
            ],
        ),
    ]
