# Generated by Django 3.2.9 on 2021-12-11 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('General', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('isDeliverable', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('avgRating', models.IntegerField(default=0)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_cover_image', to='General.mediafile')),
                ('gallery', models.ManyToManyField(blank=True, to='General.MediaFile', verbose_name='item_gallery_images')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
