# Generated by Django 3.2.9 on 2021-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_category_storecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(to='Product.Product'),
        ),
    ]
