# Generated by Django 3.2.9 on 2021-12-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
        ('Product', '0003_category_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('coverImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='General.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.attribute')),
                ('attributeItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.attributeitem')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, to='Product.VariantItem')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='items',
            field=models.ManyToManyField(blank=True, to='Product.AttributeItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ManyToManyField(blank=True, to='Product.Variant'),
        ),
    ]
